// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatPack.proto

package com.leo.chat.proto;

public final class ChatPackOuterClass {
  private ChatPackOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatPackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatPack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The type.
     */
    com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type getType();

    /**
     * <code>.data.Subscribe subscribe = 3;</code>
     * @return Whether the subscribe field is set.
     */
    boolean hasSubscribe();
    /**
     * <code>.data.Subscribe subscribe = 3;</code>
     * @return The subscribe.
     */
    com.leo.chat.proto.data.SubscribeOuterClass.Subscribe getSubscribe();
    /**
     * <code>.data.Subscribe subscribe = 3;</code>
     */
    com.leo.chat.proto.data.SubscribeOuterClass.SubscribeOrBuilder getSubscribeOrBuilder();

    /**
     * <code>.data.UnSubscribe unsubscribe = 4;</code>
     * @return Whether the unsubscribe field is set.
     */
    boolean hasUnsubscribe();
    /**
     * <code>.data.UnSubscribe unsubscribe = 4;</code>
     * @return The unsubscribe.
     */
    com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe getUnsubscribe();
    /**
     * <code>.data.UnSubscribe unsubscribe = 4;</code>
     */
    com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribeOrBuilder getUnsubscribeOrBuilder();

    /**
     * <code>.data.Message message = 5;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.data.Message message = 5;</code>
     * @return The message.
     */
    com.leo.chat.proto.data.MessageOuterClass.Message getMessage();
    /**
     * <code>.data.Message message = 5;</code>
     */
    com.leo.chat.proto.data.MessageOuterClass.MessageOrBuilder getMessageOrBuilder();

    /**
     * <code>.data.Result result = 6;</code>
     * @return Whether the result field is set.
     */
    boolean hasResult();
    /**
     * <code>.data.Result result = 6;</code>
     * @return The result.
     */
    com.leo.chat.proto.data.ResultOuterClass.Result getResult();
    /**
     * <code>.data.Result result = 6;</code>
     */
    com.leo.chat.proto.data.ResultOuterClass.ResultOrBuilder getResultOrBuilder();

    public com.leo.chat.proto.ChatPackOuterClass.ChatPack.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code ChatPack}
   */
  public static final class ChatPack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatPack)
      ChatPackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatPack.newBuilder() to construct.
    private ChatPack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatPack() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatPack();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.Builder subBuilder = null;
              if (dataCase_ == 3) {
                subBuilder = ((com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 3;
              break;
            }
            case 34: {
              com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.Builder subBuilder = null;
              if (dataCase_ == 4) {
                subBuilder = ((com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 4;
              break;
            }
            case 42: {
              com.leo.chat.proto.data.MessageOuterClass.Message.Builder subBuilder = null;
              if (dataCase_ == 5) {
                subBuilder = ((com.leo.chat.proto.data.MessageOuterClass.Message) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.leo.chat.proto.data.MessageOuterClass.Message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.data.MessageOuterClass.Message) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 5;
              break;
            }
            case 50: {
              com.leo.chat.proto.data.ResultOuterClass.Result.Builder subBuilder = null;
              if (dataCase_ == 6) {
                subBuilder = ((com.leo.chat.proto.data.ResultOuterClass.Result) data_).toBuilder();
              }
              data_ =
                  input.readMessage(com.leo.chat.proto.data.ResultOuterClass.Result.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.data.ResultOuterClass.Result) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 6;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leo.chat.proto.ChatPackOuterClass.ChatPack.class, com.leo.chat.proto.ChatPackOuterClass.ChatPack.Builder.class);
    }

    /**
     * Protobuf enum {@code ChatPack.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      /**
       * <code>PONG = 1;</code>
       */
      PONG(1),
      /**
       * <code>SUBSCRIBE = 2;</code>
       */
      SUBSCRIBE(2),
      /**
       * <code>UNSUBSCRIBE = 3;</code>
       */
      UNSUBSCRIBE(3),
      /**
       * <code>MESSAGE = 4;</code>
       */
      MESSAGE(4),
      /**
       * <code>RESULT = 5;</code>
       */
      RESULT(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;
      /**
       * <code>PONG = 1;</code>
       */
      public static final int PONG_VALUE = 1;
      /**
       * <code>SUBSCRIBE = 2;</code>
       */
      public static final int SUBSCRIBE_VALUE = 2;
      /**
       * <code>UNSUBSCRIBE = 3;</code>
       */
      public static final int UNSUBSCRIBE_VALUE = 3;
      /**
       * <code>MESSAGE = 4;</code>
       */
      public static final int MESSAGE_VALUE = 4;
      /**
       * <code>RESULT = 5;</code>
       */
      public static final int RESULT_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return PING;
          case 1: return PONG;
          case 2: return SUBSCRIBE;
          case 3: return UNSUBSCRIBE;
          case 4: return MESSAGE;
          case 5: return RESULT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.leo.chat.proto.ChatPackOuterClass.ChatPack.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ChatPack.Type)
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      SUBSCRIBE(3),
      UNSUBSCRIBE(4),
      MESSAGE(5),
      RESULT(6),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 3: return SUBSCRIBE;
          case 4: return UNSUBSCRIBE;
          case 5: return MESSAGE;
          case 6: return RESULT;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type getType() {
      @SuppressWarnings("deprecation")
      com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type result = com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.valueOf(type_);
      return result == null ? com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.UNRECOGNIZED : result;
    }

    public static final int SUBSCRIBE_FIELD_NUMBER = 3;
    /**
     * <code>.data.Subscribe subscribe = 3;</code>
     * @return Whether the subscribe field is set.
     */
    @java.lang.Override
    public boolean hasSubscribe() {
      return dataCase_ == 3;
    }
    /**
     * <code>.data.Subscribe subscribe = 3;</code>
     * @return The subscribe.
     */
    @java.lang.Override
    public com.leo.chat.proto.data.SubscribeOuterClass.Subscribe getSubscribe() {
      if (dataCase_ == 3) {
         return (com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_;
      }
      return com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.getDefaultInstance();
    }
    /**
     * <code>.data.Subscribe subscribe = 3;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.data.SubscribeOuterClass.SubscribeOrBuilder getSubscribeOrBuilder() {
      if (dataCase_ == 3) {
         return (com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_;
      }
      return com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.getDefaultInstance();
    }

    public static final int UNSUBSCRIBE_FIELD_NUMBER = 4;
    /**
     * <code>.data.UnSubscribe unsubscribe = 4;</code>
     * @return Whether the unsubscribe field is set.
     */
    @java.lang.Override
    public boolean hasUnsubscribe() {
      return dataCase_ == 4;
    }
    /**
     * <code>.data.UnSubscribe unsubscribe = 4;</code>
     * @return The unsubscribe.
     */
    @java.lang.Override
    public com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe getUnsubscribe() {
      if (dataCase_ == 4) {
         return (com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_;
      }
      return com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.getDefaultInstance();
    }
    /**
     * <code>.data.UnSubscribe unsubscribe = 4;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribeOrBuilder getUnsubscribeOrBuilder() {
      if (dataCase_ == 4) {
         return (com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_;
      }
      return com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.getDefaultInstance();
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    /**
     * <code>.data.Message message = 5;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return dataCase_ == 5;
    }
    /**
     * <code>.data.Message message = 5;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.leo.chat.proto.data.MessageOuterClass.Message getMessage() {
      if (dataCase_ == 5) {
         return (com.leo.chat.proto.data.MessageOuterClass.Message) data_;
      }
      return com.leo.chat.proto.data.MessageOuterClass.Message.getDefaultInstance();
    }
    /**
     * <code>.data.Message message = 5;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.data.MessageOuterClass.MessageOrBuilder getMessageOrBuilder() {
      if (dataCase_ == 5) {
         return (com.leo.chat.proto.data.MessageOuterClass.Message) data_;
      }
      return com.leo.chat.proto.data.MessageOuterClass.Message.getDefaultInstance();
    }

    public static final int RESULT_FIELD_NUMBER = 6;
    /**
     * <code>.data.Result result = 6;</code>
     * @return Whether the result field is set.
     */
    @java.lang.Override
    public boolean hasResult() {
      return dataCase_ == 6;
    }
    /**
     * <code>.data.Result result = 6;</code>
     * @return The result.
     */
    @java.lang.Override
    public com.leo.chat.proto.data.ResultOuterClass.Result getResult() {
      if (dataCase_ == 6) {
         return (com.leo.chat.proto.data.ResultOuterClass.Result) data_;
      }
      return com.leo.chat.proto.data.ResultOuterClass.Result.getDefaultInstance();
    }
    /**
     * <code>.data.Result result = 6;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.data.ResultOuterClass.ResultOrBuilder getResultOrBuilder() {
      if (dataCase_ == 6) {
         return (com.leo.chat.proto.data.ResultOuterClass.Result) data_;
      }
      return com.leo.chat.proto.data.ResultOuterClass.Result.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.PING.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (dataCase_ == 3) {
        output.writeMessage(3, (com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_);
      }
      if (dataCase_ == 4) {
        output.writeMessage(4, (com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_);
      }
      if (dataCase_ == 5) {
        output.writeMessage(5, (com.leo.chat.proto.data.MessageOuterClass.Message) data_);
      }
      if (dataCase_ == 6) {
        output.writeMessage(6, (com.leo.chat.proto.data.ResultOuterClass.Result) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_);
      }
      if (dataCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_);
      }
      if (dataCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (com.leo.chat.proto.data.MessageOuterClass.Message) data_);
      }
      if (dataCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (com.leo.chat.proto.data.ResultOuterClass.Result) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leo.chat.proto.ChatPackOuterClass.ChatPack)) {
        return super.equals(obj);
      }
      com.leo.chat.proto.ChatPackOuterClass.ChatPack other = (com.leo.chat.proto.ChatPackOuterClass.ChatPack) obj;

      if (type_ != other.type_) return false;
      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 3:
          if (!getSubscribe()
              .equals(other.getSubscribe())) return false;
          break;
        case 4:
          if (!getUnsubscribe()
              .equals(other.getUnsubscribe())) return false;
          break;
        case 5:
          if (!getMessage()
              .equals(other.getMessage())) return false;
          break;
        case 6:
          if (!getResult()
              .equals(other.getResult())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (dataCase_) {
        case 3:
          hash = (37 * hash) + SUBSCRIBE_FIELD_NUMBER;
          hash = (53 * hash) + getSubscribe().hashCode();
          break;
        case 4:
          hash = (37 * hash) + UNSUBSCRIBE_FIELD_NUMBER;
          hash = (53 * hash) + getUnsubscribe().hashCode();
          break;
        case 5:
          hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getMessage().hashCode();
          break;
        case 6:
          hash = (37 * hash) + RESULT_FIELD_NUMBER;
          hash = (53 * hash) + getResult().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leo.chat.proto.ChatPackOuterClass.ChatPack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatPack)
        com.leo.chat.proto.ChatPackOuterClass.ChatPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leo.chat.proto.ChatPackOuterClass.ChatPack.class, com.leo.chat.proto.ChatPackOuterClass.ChatPack.Builder.class);
      }

      // Construct using com.leo.chat.proto.ChatPackOuterClass.ChatPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_descriptor;
      }

      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack getDefaultInstanceForType() {
        return com.leo.chat.proto.ChatPackOuterClass.ChatPack.getDefaultInstance();
      }

      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack build() {
        com.leo.chat.proto.ChatPackOuterClass.ChatPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack buildPartial() {
        com.leo.chat.proto.ChatPackOuterClass.ChatPack result = new com.leo.chat.proto.ChatPackOuterClass.ChatPack(this);
        result.type_ = type_;
        if (dataCase_ == 3) {
          if (subscribeBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = subscribeBuilder_.build();
          }
        }
        if (dataCase_ == 4) {
          if (unsubscribeBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = unsubscribeBuilder_.build();
          }
        }
        if (dataCase_ == 5) {
          if (messageBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = messageBuilder_.build();
          }
        }
        if (dataCase_ == 6) {
          if (resultBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = resultBuilder_.build();
          }
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leo.chat.proto.ChatPackOuterClass.ChatPack) {
          return mergeFrom((com.leo.chat.proto.ChatPackOuterClass.ChatPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leo.chat.proto.ChatPackOuterClass.ChatPack other) {
        if (other == com.leo.chat.proto.ChatPackOuterClass.ChatPack.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getDataCase()) {
          case SUBSCRIBE: {
            mergeSubscribe(other.getSubscribe());
            break;
          }
          case UNSUBSCRIBE: {
            mergeUnsubscribe(other.getUnsubscribe());
            break;
          }
          case MESSAGE: {
            mergeMessage(other.getMessage());
            break;
          }
          case RESULT: {
            mergeResult(other.getResult());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leo.chat.proto.ChatPackOuterClass.ChatPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leo.chat.proto.ChatPackOuterClass.ChatPack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type getType() {
        @SuppressWarnings("deprecation")
        com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type result = com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.valueOf(type_);
        return result == null ? com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.SubscribeOuterClass.Subscribe, com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.Builder, com.leo.chat.proto.data.SubscribeOuterClass.SubscribeOrBuilder> subscribeBuilder_;
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       * @return Whether the subscribe field is set.
       */
      @java.lang.Override
      public boolean hasSubscribe() {
        return dataCase_ == 3;
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       * @return The subscribe.
       */
      @java.lang.Override
      public com.leo.chat.proto.data.SubscribeOuterClass.Subscribe getSubscribe() {
        if (subscribeBuilder_ == null) {
          if (dataCase_ == 3) {
            return (com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_;
          }
          return com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.getDefaultInstance();
        } else {
          if (dataCase_ == 3) {
            return subscribeBuilder_.getMessage();
          }
          return com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.getDefaultInstance();
        }
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       */
      public Builder setSubscribe(com.leo.chat.proto.data.SubscribeOuterClass.Subscribe value) {
        if (subscribeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          subscribeBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       */
      public Builder setSubscribe(
          com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.Builder builderForValue) {
        if (subscribeBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          subscribeBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       */
      public Builder mergeSubscribe(com.leo.chat.proto.data.SubscribeOuterClass.Subscribe value) {
        if (subscribeBuilder_ == null) {
          if (dataCase_ == 3 &&
              data_ != com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.getDefaultInstance()) {
            data_ = com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.newBuilder((com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 3) {
            subscribeBuilder_.mergeFrom(value);
          }
          subscribeBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       */
      public Builder clearSubscribe() {
        if (subscribeBuilder_ == null) {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
          }
          subscribeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       */
      public com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.Builder getSubscribeBuilder() {
        return getSubscribeFieldBuilder().getBuilder();
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.data.SubscribeOuterClass.SubscribeOrBuilder getSubscribeOrBuilder() {
        if ((dataCase_ == 3) && (subscribeBuilder_ != null)) {
          return subscribeBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 3) {
            return (com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_;
          }
          return com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.getDefaultInstance();
        }
      }
      /**
       * <code>.data.Subscribe subscribe = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.SubscribeOuterClass.Subscribe, com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.Builder, com.leo.chat.proto.data.SubscribeOuterClass.SubscribeOrBuilder> 
          getSubscribeFieldBuilder() {
        if (subscribeBuilder_ == null) {
          if (!(dataCase_ == 3)) {
            data_ = com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.getDefaultInstance();
          }
          subscribeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.data.SubscribeOuterClass.Subscribe, com.leo.chat.proto.data.SubscribeOuterClass.Subscribe.Builder, com.leo.chat.proto.data.SubscribeOuterClass.SubscribeOrBuilder>(
                  (com.leo.chat.proto.data.SubscribeOuterClass.Subscribe) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 3;
        onChanged();;
        return subscribeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe, com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.Builder, com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribeOrBuilder> unsubscribeBuilder_;
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       * @return Whether the unsubscribe field is set.
       */
      @java.lang.Override
      public boolean hasUnsubscribe() {
        return dataCase_ == 4;
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       * @return The unsubscribe.
       */
      @java.lang.Override
      public com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe getUnsubscribe() {
        if (unsubscribeBuilder_ == null) {
          if (dataCase_ == 4) {
            return (com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_;
          }
          return com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.getDefaultInstance();
        } else {
          if (dataCase_ == 4) {
            return unsubscribeBuilder_.getMessage();
          }
          return com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.getDefaultInstance();
        }
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       */
      public Builder setUnsubscribe(com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe value) {
        if (unsubscribeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          unsubscribeBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       */
      public Builder setUnsubscribe(
          com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.Builder builderForValue) {
        if (unsubscribeBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          unsubscribeBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       */
      public Builder mergeUnsubscribe(com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe value) {
        if (unsubscribeBuilder_ == null) {
          if (dataCase_ == 4 &&
              data_ != com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.getDefaultInstance()) {
            data_ = com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.newBuilder((com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 4) {
            unsubscribeBuilder_.mergeFrom(value);
          }
          unsubscribeBuilder_.setMessage(value);
        }
        dataCase_ = 4;
        return this;
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       */
      public Builder clearUnsubscribe() {
        if (unsubscribeBuilder_ == null) {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 4) {
            dataCase_ = 0;
            data_ = null;
          }
          unsubscribeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       */
      public com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.Builder getUnsubscribeBuilder() {
        return getUnsubscribeFieldBuilder().getBuilder();
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribeOrBuilder getUnsubscribeOrBuilder() {
        if ((dataCase_ == 4) && (unsubscribeBuilder_ != null)) {
          return unsubscribeBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 4) {
            return (com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_;
          }
          return com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.getDefaultInstance();
        }
      }
      /**
       * <code>.data.UnSubscribe unsubscribe = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe, com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.Builder, com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribeOrBuilder> 
          getUnsubscribeFieldBuilder() {
        if (unsubscribeBuilder_ == null) {
          if (!(dataCase_ == 4)) {
            data_ = com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.getDefaultInstance();
          }
          unsubscribeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe, com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe.Builder, com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribeOrBuilder>(
                  (com.leo.chat.proto.data.UnSubscribeOuterClass.UnSubscribe) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 4;
        onChanged();;
        return unsubscribeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.MessageOuterClass.Message, com.leo.chat.proto.data.MessageOuterClass.Message.Builder, com.leo.chat.proto.data.MessageOuterClass.MessageOrBuilder> messageBuilder_;
      /**
       * <code>.data.Message message = 5;</code>
       * @return Whether the message field is set.
       */
      @java.lang.Override
      public boolean hasMessage() {
        return dataCase_ == 5;
      }
      /**
       * <code>.data.Message message = 5;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.leo.chat.proto.data.MessageOuterClass.Message getMessage() {
        if (messageBuilder_ == null) {
          if (dataCase_ == 5) {
            return (com.leo.chat.proto.data.MessageOuterClass.Message) data_;
          }
          return com.leo.chat.proto.data.MessageOuterClass.Message.getDefaultInstance();
        } else {
          if (dataCase_ == 5) {
            return messageBuilder_.getMessage();
          }
          return com.leo.chat.proto.data.MessageOuterClass.Message.getDefaultInstance();
        }
      }
      /**
       * <code>.data.Message message = 5;</code>
       */
      public Builder setMessage(com.leo.chat.proto.data.MessageOuterClass.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.data.Message message = 5;</code>
       */
      public Builder setMessage(
          com.leo.chat.proto.data.MessageOuterClass.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.data.Message message = 5;</code>
       */
      public Builder mergeMessage(com.leo.chat.proto.data.MessageOuterClass.Message value) {
        if (messageBuilder_ == null) {
          if (dataCase_ == 5 &&
              data_ != com.leo.chat.proto.data.MessageOuterClass.Message.getDefaultInstance()) {
            data_ = com.leo.chat.proto.data.MessageOuterClass.Message.newBuilder((com.leo.chat.proto.data.MessageOuterClass.Message) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 5) {
            messageBuilder_.mergeFrom(value);
          }
          messageBuilder_.setMessage(value);
        }
        dataCase_ = 5;
        return this;
      }
      /**
       * <code>.data.Message message = 5;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 5) {
            dataCase_ = 0;
            data_ = null;
          }
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.data.Message message = 5;</code>
       */
      public com.leo.chat.proto.data.MessageOuterClass.Message.Builder getMessageBuilder() {
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.data.Message message = 5;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.data.MessageOuterClass.MessageOrBuilder getMessageOrBuilder() {
        if ((dataCase_ == 5) && (messageBuilder_ != null)) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 5) {
            return (com.leo.chat.proto.data.MessageOuterClass.Message) data_;
          }
          return com.leo.chat.proto.data.MessageOuterClass.Message.getDefaultInstance();
        }
      }
      /**
       * <code>.data.Message message = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.MessageOuterClass.Message, com.leo.chat.proto.data.MessageOuterClass.Message.Builder, com.leo.chat.proto.data.MessageOuterClass.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          if (!(dataCase_ == 5)) {
            data_ = com.leo.chat.proto.data.MessageOuterClass.Message.getDefaultInstance();
          }
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.data.MessageOuterClass.Message, com.leo.chat.proto.data.MessageOuterClass.Message.Builder, com.leo.chat.proto.data.MessageOuterClass.MessageOrBuilder>(
                  (com.leo.chat.proto.data.MessageOuterClass.Message) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 5;
        onChanged();;
        return messageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.ResultOuterClass.Result, com.leo.chat.proto.data.ResultOuterClass.Result.Builder, com.leo.chat.proto.data.ResultOuterClass.ResultOrBuilder> resultBuilder_;
      /**
       * <code>.data.Result result = 6;</code>
       * @return Whether the result field is set.
       */
      @java.lang.Override
      public boolean hasResult() {
        return dataCase_ == 6;
      }
      /**
       * <code>.data.Result result = 6;</code>
       * @return The result.
       */
      @java.lang.Override
      public com.leo.chat.proto.data.ResultOuterClass.Result getResult() {
        if (resultBuilder_ == null) {
          if (dataCase_ == 6) {
            return (com.leo.chat.proto.data.ResultOuterClass.Result) data_;
          }
          return com.leo.chat.proto.data.ResultOuterClass.Result.getDefaultInstance();
        } else {
          if (dataCase_ == 6) {
            return resultBuilder_.getMessage();
          }
          return com.leo.chat.proto.data.ResultOuterClass.Result.getDefaultInstance();
        }
      }
      /**
       * <code>.data.Result result = 6;</code>
       */
      public Builder setResult(com.leo.chat.proto.data.ResultOuterClass.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        dataCase_ = 6;
        return this;
      }
      /**
       * <code>.data.Result result = 6;</code>
       */
      public Builder setResult(
          com.leo.chat.proto.data.ResultOuterClass.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 6;
        return this;
      }
      /**
       * <code>.data.Result result = 6;</code>
       */
      public Builder mergeResult(com.leo.chat.proto.data.ResultOuterClass.Result value) {
        if (resultBuilder_ == null) {
          if (dataCase_ == 6 &&
              data_ != com.leo.chat.proto.data.ResultOuterClass.Result.getDefaultInstance()) {
            data_ = com.leo.chat.proto.data.ResultOuterClass.Result.newBuilder((com.leo.chat.proto.data.ResultOuterClass.Result) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 6) {
            resultBuilder_.mergeFrom(value);
          }
          resultBuilder_.setMessage(value);
        }
        dataCase_ = 6;
        return this;
      }
      /**
       * <code>.data.Result result = 6;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          if (dataCase_ == 6) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 6) {
            dataCase_ = 0;
            data_ = null;
          }
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.data.Result result = 6;</code>
       */
      public com.leo.chat.proto.data.ResultOuterClass.Result.Builder getResultBuilder() {
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.data.Result result = 6;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.data.ResultOuterClass.ResultOrBuilder getResultOrBuilder() {
        if ((dataCase_ == 6) && (resultBuilder_ != null)) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 6) {
            return (com.leo.chat.proto.data.ResultOuterClass.Result) data_;
          }
          return com.leo.chat.proto.data.ResultOuterClass.Result.getDefaultInstance();
        }
      }
      /**
       * <code>.data.Result result = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.data.ResultOuterClass.Result, com.leo.chat.proto.data.ResultOuterClass.Result.Builder, com.leo.chat.proto.data.ResultOuterClass.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          if (!(dataCase_ == 6)) {
            data_ = com.leo.chat.proto.data.ResultOuterClass.Result.getDefaultInstance();
          }
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.data.ResultOuterClass.Result, com.leo.chat.proto.data.ResultOuterClass.Result.Builder, com.leo.chat.proto.data.ResultOuterClass.ResultOrBuilder>(
                  (com.leo.chat.proto.data.ResultOuterClass.Result) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 6;
        onChanged();;
        return resultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatPack)
    }

    // @@protoc_insertion_point(class_scope:ChatPack)
    private static final com.leo.chat.proto.ChatPackOuterClass.ChatPack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leo.chat.proto.ChatPackOuterClass.ChatPack();
    }

    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatPack>
        PARSER = new com.google.protobuf.AbstractParser<ChatPack>() {
      @java.lang.Override
      public ChatPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatPack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatPack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatPack> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.leo.chat.proto.ChatPackOuterClass.ChatPack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatPack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatPack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ChatPack.proto\032\022data/Message.proto\032\024da" +
      "ta/Subscribe.proto\032\026data/UnSubscribe.pro" +
      "to\032\021data/Result.proto\"\227\002\n\010ChatPack\022\034\n\004ty" +
      "pe\030\001 \001(\0162\016.ChatPack.Type\022$\n\tsubscribe\030\003 " +
      "\001(\0132\017.data.SubscribeH\000\022(\n\013unsubscribe\030\004 " +
      "\001(\0132\021.data.UnSubscribeH\000\022 \n\007message\030\005 \001(" +
      "\0132\r.data.MessageH\000\022\036\n\006result\030\006 \001(\0132\014.dat" +
      "a.ResultH\000\"S\n\004Type\022\010\n\004PING\020\000\022\010\n\004PONG\020\001\022\r" +
      "\n\tSUBSCRIBE\020\002\022\017\n\013UNSUBSCRIBE\020\003\022\013\n\007MESSAG" +
      "E\020\004\022\n\n\006RESULT\020\005B\006\n\004dataB\024\n\022com.leo.chat." +
      "protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leo.chat.proto.data.MessageOuterClass.getDescriptor(),
          com.leo.chat.proto.data.SubscribeOuterClass.getDescriptor(),
          com.leo.chat.proto.data.UnSubscribeOuterClass.getDescriptor(),
          com.leo.chat.proto.data.ResultOuterClass.getDescriptor(),
        });
    internal_static_ChatPack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatPack_descriptor,
        new java.lang.String[] { "Type", "Subscribe", "Unsubscribe", "Message", "Result", "Data", });
    com.leo.chat.proto.data.MessageOuterClass.getDescriptor();
    com.leo.chat.proto.data.SubscribeOuterClass.getDescriptor();
    com.leo.chat.proto.data.UnSubscribeOuterClass.getDescriptor();
    com.leo.chat.proto.data.ResultOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
