// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatPack.proto

package com.leo.chat.proto;

public final class ChatPackOuterClass {
  private ChatPackOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatPackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatPack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The type.
     */
    com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type getType();

    /**
     * <code>fixed64 sendTime = 2;</code>
     * @return The sendTime.
     */
    long getSendTime();

    /**
     * <code>.message.WordMessage wordMessage = 4;</code>
     * @return Whether the wordMessage field is set.
     */
    boolean hasWordMessage();
    /**
     * <code>.message.WordMessage wordMessage = 4;</code>
     * @return The wordMessage.
     */
    com.leo.chat.proto.message.WordMessageOuterClass.WordMessage getWordMessage();
    /**
     * <code>.message.WordMessage wordMessage = 4;</code>
     */
    com.leo.chat.proto.message.WordMessageOuterClass.WordMessageOrBuilder getWordMessageOrBuilder();

    /**
     * <code>.message.VideoMessage videoMessage = 5;</code>
     * @return Whether the videoMessage field is set.
     */
    boolean hasVideoMessage();
    /**
     * <code>.message.VideoMessage videoMessage = 5;</code>
     * @return The videoMessage.
     */
    com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage getVideoMessage();
    /**
     * <code>.message.VideoMessage videoMessage = 5;</code>
     */
    com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessageOrBuilder getVideoMessageOrBuilder();

    /**
     * <code>.message.AudioMessage audioMessage = 6;</code>
     * @return Whether the audioMessage field is set.
     */
    boolean hasAudioMessage();
    /**
     * <code>.message.AudioMessage audioMessage = 6;</code>
     * @return The audioMessage.
     */
    com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage getAudioMessage();
    /**
     * <code>.message.AudioMessage audioMessage = 6;</code>
     */
    com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessageOrBuilder getAudioMessageOrBuilder();

    /**
     * <code>.message.FileMessage fileMessage = 7;</code>
     * @return Whether the fileMessage field is set.
     */
    boolean hasFileMessage();
    /**
     * <code>.message.FileMessage fileMessage = 7;</code>
     * @return The fileMessage.
     */
    com.leo.chat.proto.message.FileMessageOuterClass.FileMessage getFileMessage();
    /**
     * <code>.message.FileMessage fileMessage = 7;</code>
     */
    com.leo.chat.proto.message.FileMessageOuterClass.FileMessageOrBuilder getFileMessageOrBuilder();

    public com.leo.chat.proto.ChatPackOuterClass.ChatPack.MessageCase getMessageCase();
  }
  /**
   * Protobuf type {@code ChatPack}
   */
  public static final class ChatPack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatPack)
      ChatPackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatPack.newBuilder() to construct.
    private ChatPack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatPack() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatPack();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 17: {

              sendTime_ = input.readFixed64();
              break;
            }
            case 34: {
              com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.Builder subBuilder = null;
              if (messageCase_ == 4) {
                subBuilder = ((com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 4;
              break;
            }
            case 42: {
              com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.Builder subBuilder = null;
              if (messageCase_ == 5) {
                subBuilder = ((com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 5;
              break;
            }
            case 50: {
              com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.Builder subBuilder = null;
              if (messageCase_ == 6) {
                subBuilder = ((com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 6;
              break;
            }
            case 58: {
              com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.Builder subBuilder = null;
              if (messageCase_ == 7) {
                subBuilder = ((com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 7;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leo.chat.proto.ChatPackOuterClass.ChatPack.class, com.leo.chat.proto.ChatPackOuterClass.ChatPack.Builder.class);
    }

    /**
     * Protobuf enum {@code ChatPack.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      /**
       * <code>PONG = 1;</code>
       */
      PONG(1),
      /**
       * <code>WORD = 2;</code>
       */
      WORD(2),
      /**
       * <code>AUDIO = 3;</code>
       */
      AUDIO(3),
      /**
       * <code>VIDEO = 4;</code>
       */
      VIDEO(4),
      /**
       * <code>FILE = 5;</code>
       */
      FILE(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;
      /**
       * <code>PONG = 1;</code>
       */
      public static final int PONG_VALUE = 1;
      /**
       * <code>WORD = 2;</code>
       */
      public static final int WORD_VALUE = 2;
      /**
       * <code>AUDIO = 3;</code>
       */
      public static final int AUDIO_VALUE = 3;
      /**
       * <code>VIDEO = 4;</code>
       */
      public static final int VIDEO_VALUE = 4;
      /**
       * <code>FILE = 5;</code>
       */
      public static final int FILE_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return PING;
          case 1: return PONG;
          case 2: return WORD;
          case 3: return AUDIO;
          case 4: return VIDEO;
          case 5: return FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.leo.chat.proto.ChatPackOuterClass.ChatPack.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ChatPack.Type)
    }

    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      WORDMESSAGE(4),
      VIDEOMESSAGE(5),
      AUDIOMESSAGE(6),
      FILEMESSAGE(7),
      MESSAGE_NOT_SET(0);
      private final int value;
      private MessageCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageCase forNumber(int value) {
        switch (value) {
          case 4: return WORDMESSAGE;
          case 5: return VIDEOMESSAGE;
          case 6: return AUDIOMESSAGE;
          case 7: return FILEMESSAGE;
          case 0: return MESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.ChatPack.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type getType() {
      @SuppressWarnings("deprecation")
      com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type result = com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.valueOf(type_);
      return result == null ? com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.UNRECOGNIZED : result;
    }

    public static final int SENDTIME_FIELD_NUMBER = 2;
    private long sendTime_;
    /**
     * <code>fixed64 sendTime = 2;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }

    public static final int WORDMESSAGE_FIELD_NUMBER = 4;
    /**
     * <code>.message.WordMessage wordMessage = 4;</code>
     * @return Whether the wordMessage field is set.
     */
    @java.lang.Override
    public boolean hasWordMessage() {
      return messageCase_ == 4;
    }
    /**
     * <code>.message.WordMessage wordMessage = 4;</code>
     * @return The wordMessage.
     */
    @java.lang.Override
    public com.leo.chat.proto.message.WordMessageOuterClass.WordMessage getWordMessage() {
      if (messageCase_ == 4) {
         return (com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_;
      }
      return com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.getDefaultInstance();
    }
    /**
     * <code>.message.WordMessage wordMessage = 4;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.message.WordMessageOuterClass.WordMessageOrBuilder getWordMessageOrBuilder() {
      if (messageCase_ == 4) {
         return (com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_;
      }
      return com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.getDefaultInstance();
    }

    public static final int VIDEOMESSAGE_FIELD_NUMBER = 5;
    /**
     * <code>.message.VideoMessage videoMessage = 5;</code>
     * @return Whether the videoMessage field is set.
     */
    @java.lang.Override
    public boolean hasVideoMessage() {
      return messageCase_ == 5;
    }
    /**
     * <code>.message.VideoMessage videoMessage = 5;</code>
     * @return The videoMessage.
     */
    @java.lang.Override
    public com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage getVideoMessage() {
      if (messageCase_ == 5) {
         return (com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_;
      }
      return com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.getDefaultInstance();
    }
    /**
     * <code>.message.VideoMessage videoMessage = 5;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessageOrBuilder getVideoMessageOrBuilder() {
      if (messageCase_ == 5) {
         return (com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_;
      }
      return com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.getDefaultInstance();
    }

    public static final int AUDIOMESSAGE_FIELD_NUMBER = 6;
    /**
     * <code>.message.AudioMessage audioMessage = 6;</code>
     * @return Whether the audioMessage field is set.
     */
    @java.lang.Override
    public boolean hasAudioMessage() {
      return messageCase_ == 6;
    }
    /**
     * <code>.message.AudioMessage audioMessage = 6;</code>
     * @return The audioMessage.
     */
    @java.lang.Override
    public com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage getAudioMessage() {
      if (messageCase_ == 6) {
         return (com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_;
      }
      return com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.getDefaultInstance();
    }
    /**
     * <code>.message.AudioMessage audioMessage = 6;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessageOrBuilder getAudioMessageOrBuilder() {
      if (messageCase_ == 6) {
         return (com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_;
      }
      return com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.getDefaultInstance();
    }

    public static final int FILEMESSAGE_FIELD_NUMBER = 7;
    /**
     * <code>.message.FileMessage fileMessage = 7;</code>
     * @return Whether the fileMessage field is set.
     */
    @java.lang.Override
    public boolean hasFileMessage() {
      return messageCase_ == 7;
    }
    /**
     * <code>.message.FileMessage fileMessage = 7;</code>
     * @return The fileMessage.
     */
    @java.lang.Override
    public com.leo.chat.proto.message.FileMessageOuterClass.FileMessage getFileMessage() {
      if (messageCase_ == 7) {
         return (com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_;
      }
      return com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.getDefaultInstance();
    }
    /**
     * <code>.message.FileMessage fileMessage = 7;</code>
     */
    @java.lang.Override
    public com.leo.chat.proto.message.FileMessageOuterClass.FileMessageOrBuilder getFileMessageOrBuilder() {
      if (messageCase_ == 7) {
         return (com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_;
      }
      return com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.PING.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (sendTime_ != 0L) {
        output.writeFixed64(2, sendTime_);
      }
      if (messageCase_ == 4) {
        output.writeMessage(4, (com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_);
      }
      if (messageCase_ == 5) {
        output.writeMessage(5, (com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_);
      }
      if (messageCase_ == 6) {
        output.writeMessage(6, (com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_);
      }
      if (messageCase_ == 7) {
        output.writeMessage(7, (com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, sendTime_);
      }
      if (messageCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_);
      }
      if (messageCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_);
      }
      if (messageCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_);
      }
      if (messageCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leo.chat.proto.ChatPackOuterClass.ChatPack)) {
        return super.equals(obj);
      }
      com.leo.chat.proto.ChatPackOuterClass.ChatPack other = (com.leo.chat.proto.ChatPackOuterClass.ChatPack) obj;

      if (type_ != other.type_) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!getMessageCase().equals(other.getMessageCase())) return false;
      switch (messageCase_) {
        case 4:
          if (!getWordMessage()
              .equals(other.getWordMessage())) return false;
          break;
        case 5:
          if (!getVideoMessage()
              .equals(other.getVideoMessage())) return false;
          break;
        case 6:
          if (!getAudioMessage()
              .equals(other.getAudioMessage())) return false;
          break;
        case 7:
          if (!getFileMessage()
              .equals(other.getFileMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      switch (messageCase_) {
        case 4:
          hash = (37 * hash) + WORDMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getWordMessage().hashCode();
          break;
        case 5:
          hash = (37 * hash) + VIDEOMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getVideoMessage().hashCode();
          break;
        case 6:
          hash = (37 * hash) + AUDIOMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getAudioMessage().hashCode();
          break;
        case 7:
          hash = (37 * hash) + FILEMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getFileMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leo.chat.proto.ChatPackOuterClass.ChatPack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatPack)
        com.leo.chat.proto.ChatPackOuterClass.ChatPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leo.chat.proto.ChatPackOuterClass.ChatPack.class, com.leo.chat.proto.ChatPackOuterClass.ChatPack.Builder.class);
      }

      // Construct using com.leo.chat.proto.ChatPackOuterClass.ChatPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        sendTime_ = 0L;

        messageCase_ = 0;
        message_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leo.chat.proto.ChatPackOuterClass.internal_static_ChatPack_descriptor;
      }

      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack getDefaultInstanceForType() {
        return com.leo.chat.proto.ChatPackOuterClass.ChatPack.getDefaultInstance();
      }

      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack build() {
        com.leo.chat.proto.ChatPackOuterClass.ChatPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack buildPartial() {
        com.leo.chat.proto.ChatPackOuterClass.ChatPack result = new com.leo.chat.proto.ChatPackOuterClass.ChatPack(this);
        result.type_ = type_;
        result.sendTime_ = sendTime_;
        if (messageCase_ == 4) {
          if (wordMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = wordMessageBuilder_.build();
          }
        }
        if (messageCase_ == 5) {
          if (videoMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = videoMessageBuilder_.build();
          }
        }
        if (messageCase_ == 6) {
          if (audioMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = audioMessageBuilder_.build();
          }
        }
        if (messageCase_ == 7) {
          if (fileMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = fileMessageBuilder_.build();
          }
        }
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leo.chat.proto.ChatPackOuterClass.ChatPack) {
          return mergeFrom((com.leo.chat.proto.ChatPackOuterClass.ChatPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leo.chat.proto.ChatPackOuterClass.ChatPack other) {
        if (other == com.leo.chat.proto.ChatPackOuterClass.ChatPack.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        switch (other.getMessageCase()) {
          case WORDMESSAGE: {
            mergeWordMessage(other.getWordMessage());
            break;
          }
          case VIDEOMESSAGE: {
            mergeVideoMessage(other.getVideoMessage());
            break;
          }
          case AUDIOMESSAGE: {
            mergeAudioMessage(other.getAudioMessage());
            break;
          }
          case FILEMESSAGE: {
            mergeFileMessage(other.getFileMessage());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leo.chat.proto.ChatPackOuterClass.ChatPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leo.chat.proto.ChatPackOuterClass.ChatPack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.forNumber(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type getType() {
        @SuppressWarnings("deprecation")
        com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type result = com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.valueOf(type_);
        return result == null ? com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.leo.chat.proto.ChatPackOuterClass.ChatPack.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ChatPack.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <code>fixed64 sendTime = 2;</code>
       * @return The sendTime.
       */
      @java.lang.Override
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>fixed64 sendTime = 2;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 sendTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.WordMessageOuterClass.WordMessage, com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.Builder, com.leo.chat.proto.message.WordMessageOuterClass.WordMessageOrBuilder> wordMessageBuilder_;
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       * @return Whether the wordMessage field is set.
       */
      @java.lang.Override
      public boolean hasWordMessage() {
        return messageCase_ == 4;
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       * @return The wordMessage.
       */
      @java.lang.Override
      public com.leo.chat.proto.message.WordMessageOuterClass.WordMessage getWordMessage() {
        if (wordMessageBuilder_ == null) {
          if (messageCase_ == 4) {
            return (com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_;
          }
          return com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 4) {
            return wordMessageBuilder_.getMessage();
          }
          return com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       */
      public Builder setWordMessage(com.leo.chat.proto.message.WordMessageOuterClass.WordMessage value) {
        if (wordMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          wordMessageBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       */
      public Builder setWordMessage(
          com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.Builder builderForValue) {
        if (wordMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          wordMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       */
      public Builder mergeWordMessage(com.leo.chat.proto.message.WordMessageOuterClass.WordMessage value) {
        if (wordMessageBuilder_ == null) {
          if (messageCase_ == 4 &&
              message_ != com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.getDefaultInstance()) {
            message_ = com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.newBuilder((com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 4) {
            wordMessageBuilder_.mergeFrom(value);
          }
          wordMessageBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       */
      public Builder clearWordMessage() {
        if (wordMessageBuilder_ == null) {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
          }
          wordMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       */
      public com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.Builder getWordMessageBuilder() {
        return getWordMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.message.WordMessageOuterClass.WordMessageOrBuilder getWordMessageOrBuilder() {
        if ((messageCase_ == 4) && (wordMessageBuilder_ != null)) {
          return wordMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 4) {
            return (com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_;
          }
          return com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.WordMessage wordMessage = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.WordMessageOuterClass.WordMessage, com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.Builder, com.leo.chat.proto.message.WordMessageOuterClass.WordMessageOrBuilder> 
          getWordMessageFieldBuilder() {
        if (wordMessageBuilder_ == null) {
          if (!(messageCase_ == 4)) {
            message_ = com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.getDefaultInstance();
          }
          wordMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.message.WordMessageOuterClass.WordMessage, com.leo.chat.proto.message.WordMessageOuterClass.WordMessage.Builder, com.leo.chat.proto.message.WordMessageOuterClass.WordMessageOrBuilder>(
                  (com.leo.chat.proto.message.WordMessageOuterClass.WordMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 4;
        onChanged();;
        return wordMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage, com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.Builder, com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessageOrBuilder> videoMessageBuilder_;
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       * @return Whether the videoMessage field is set.
       */
      @java.lang.Override
      public boolean hasVideoMessage() {
        return messageCase_ == 5;
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       * @return The videoMessage.
       */
      @java.lang.Override
      public com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage getVideoMessage() {
        if (videoMessageBuilder_ == null) {
          if (messageCase_ == 5) {
            return (com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_;
          }
          return com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 5) {
            return videoMessageBuilder_.getMessage();
          }
          return com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       */
      public Builder setVideoMessage(com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage value) {
        if (videoMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          videoMessageBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       */
      public Builder setVideoMessage(
          com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.Builder builderForValue) {
        if (videoMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          videoMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       */
      public Builder mergeVideoMessage(com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage value) {
        if (videoMessageBuilder_ == null) {
          if (messageCase_ == 5 &&
              message_ != com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.getDefaultInstance()) {
            message_ = com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.newBuilder((com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 5) {
            videoMessageBuilder_.mergeFrom(value);
          }
          videoMessageBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       */
      public Builder clearVideoMessage() {
        if (videoMessageBuilder_ == null) {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
          }
          videoMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       */
      public com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.Builder getVideoMessageBuilder() {
        return getVideoMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessageOrBuilder getVideoMessageOrBuilder() {
        if ((messageCase_ == 5) && (videoMessageBuilder_ != null)) {
          return videoMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 5) {
            return (com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_;
          }
          return com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.VideoMessage videoMessage = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage, com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.Builder, com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessageOrBuilder> 
          getVideoMessageFieldBuilder() {
        if (videoMessageBuilder_ == null) {
          if (!(messageCase_ == 5)) {
            message_ = com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.getDefaultInstance();
          }
          videoMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage, com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage.Builder, com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessageOrBuilder>(
                  (com.leo.chat.proto.message.VideoMessageOuterClass.VideoMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 5;
        onChanged();;
        return videoMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage, com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.Builder, com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessageOrBuilder> audioMessageBuilder_;
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       * @return Whether the audioMessage field is set.
       */
      @java.lang.Override
      public boolean hasAudioMessage() {
        return messageCase_ == 6;
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       * @return The audioMessage.
       */
      @java.lang.Override
      public com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage getAudioMessage() {
        if (audioMessageBuilder_ == null) {
          if (messageCase_ == 6) {
            return (com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_;
          }
          return com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 6) {
            return audioMessageBuilder_.getMessage();
          }
          return com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       */
      public Builder setAudioMessage(com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage value) {
        if (audioMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          audioMessageBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       */
      public Builder setAudioMessage(
          com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.Builder builderForValue) {
        if (audioMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          audioMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       */
      public Builder mergeAudioMessage(com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage value) {
        if (audioMessageBuilder_ == null) {
          if (messageCase_ == 6 &&
              message_ != com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.getDefaultInstance()) {
            message_ = com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.newBuilder((com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 6) {
            audioMessageBuilder_.mergeFrom(value);
          }
          audioMessageBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       */
      public Builder clearAudioMessage() {
        if (audioMessageBuilder_ == null) {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
          }
          audioMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       */
      public com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.Builder getAudioMessageBuilder() {
        return getAudioMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessageOrBuilder getAudioMessageOrBuilder() {
        if ((messageCase_ == 6) && (audioMessageBuilder_ != null)) {
          return audioMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 6) {
            return (com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_;
          }
          return com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.AudioMessage audioMessage = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage, com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.Builder, com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessageOrBuilder> 
          getAudioMessageFieldBuilder() {
        if (audioMessageBuilder_ == null) {
          if (!(messageCase_ == 6)) {
            message_ = com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.getDefaultInstance();
          }
          audioMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage, com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage.Builder, com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessageOrBuilder>(
                  (com.leo.chat.proto.message.AudioMessageOuterClass.AudioMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 6;
        onChanged();;
        return audioMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.FileMessageOuterClass.FileMessage, com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.Builder, com.leo.chat.proto.message.FileMessageOuterClass.FileMessageOrBuilder> fileMessageBuilder_;
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       * @return Whether the fileMessage field is set.
       */
      @java.lang.Override
      public boolean hasFileMessage() {
        return messageCase_ == 7;
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       * @return The fileMessage.
       */
      @java.lang.Override
      public com.leo.chat.proto.message.FileMessageOuterClass.FileMessage getFileMessage() {
        if (fileMessageBuilder_ == null) {
          if (messageCase_ == 7) {
            return (com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_;
          }
          return com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 7) {
            return fileMessageBuilder_.getMessage();
          }
          return com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       */
      public Builder setFileMessage(com.leo.chat.proto.message.FileMessageOuterClass.FileMessage value) {
        if (fileMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          fileMessageBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       */
      public Builder setFileMessage(
          com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.Builder builderForValue) {
        if (fileMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          fileMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       */
      public Builder mergeFileMessage(com.leo.chat.proto.message.FileMessageOuterClass.FileMessage value) {
        if (fileMessageBuilder_ == null) {
          if (messageCase_ == 7 &&
              message_ != com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.getDefaultInstance()) {
            message_ = com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.newBuilder((com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 7) {
            fileMessageBuilder_.mergeFrom(value);
          }
          fileMessageBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       */
      public Builder clearFileMessage() {
        if (fileMessageBuilder_ == null) {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
          }
          fileMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       */
      public com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.Builder getFileMessageBuilder() {
        return getFileMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       */
      @java.lang.Override
      public com.leo.chat.proto.message.FileMessageOuterClass.FileMessageOrBuilder getFileMessageOrBuilder() {
        if ((messageCase_ == 7) && (fileMessageBuilder_ != null)) {
          return fileMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 7) {
            return (com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_;
          }
          return com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.message.FileMessage fileMessage = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leo.chat.proto.message.FileMessageOuterClass.FileMessage, com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.Builder, com.leo.chat.proto.message.FileMessageOuterClass.FileMessageOrBuilder> 
          getFileMessageFieldBuilder() {
        if (fileMessageBuilder_ == null) {
          if (!(messageCase_ == 7)) {
            message_ = com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.getDefaultInstance();
          }
          fileMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leo.chat.proto.message.FileMessageOuterClass.FileMessage, com.leo.chat.proto.message.FileMessageOuterClass.FileMessage.Builder, com.leo.chat.proto.message.FileMessageOuterClass.FileMessageOrBuilder>(
                  (com.leo.chat.proto.message.FileMessageOuterClass.FileMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 7;
        onChanged();;
        return fileMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatPack)
    }

    // @@protoc_insertion_point(class_scope:ChatPack)
    private static final com.leo.chat.proto.ChatPackOuterClass.ChatPack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leo.chat.proto.ChatPackOuterClass.ChatPack();
    }

    public static com.leo.chat.proto.ChatPackOuterClass.ChatPack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatPack>
        PARSER = new com.google.protobuf.AbstractParser<ChatPack>() {
      @java.lang.Override
      public ChatPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatPack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatPack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatPack> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.leo.chat.proto.ChatPackOuterClass.ChatPack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatPack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatPack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ChatPack.proto\032\032message/AudioMessage.p" +
      "roto\032\031message/FileMessage.proto\032\032message" +
      "/VideoMessage.proto\032\031message/WordMessage" +
      ".proto\"\303\002\n\010ChatPack\022\034\n\004type\030\001 \001(\0162\016.Chat" +
      "Pack.Type\022\020\n\010sendTime\030\002 \001(\006\022+\n\013wordMessa" +
      "ge\030\004 \001(\0132\024.message.WordMessageH\000\022-\n\014vide" +
      "oMessage\030\005 \001(\0132\025.message.VideoMessageH\000\022" +
      "-\n\014audioMessage\030\006 \001(\0132\025.message.AudioMes" +
      "sageH\000\022+\n\013fileMessage\030\007 \001(\0132\024.message.Fi" +
      "leMessageH\000\"D\n\004Type\022\010\n\004PING\020\000\022\010\n\004PONG\020\001\022" +
      "\010\n\004WORD\020\002\022\t\n\005AUDIO\020\003\022\t\n\005VIDEO\020\004\022\010\n\004FILE\020" +
      "\005B\t\n\007messageB\024\n\022com.leo.chat.protob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leo.chat.proto.message.AudioMessageOuterClass.getDescriptor(),
          com.leo.chat.proto.message.FileMessageOuterClass.getDescriptor(),
          com.leo.chat.proto.message.VideoMessageOuterClass.getDescriptor(),
          com.leo.chat.proto.message.WordMessageOuterClass.getDescriptor(),
        });
    internal_static_ChatPack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatPack_descriptor,
        new java.lang.String[] { "Type", "SendTime", "WordMessage", "VideoMessage", "AudioMessage", "FileMessage", "Message", });
    com.leo.chat.proto.message.AudioMessageOuterClass.getDescriptor();
    com.leo.chat.proto.message.FileMessageOuterClass.getDescriptor();
    com.leo.chat.proto.message.VideoMessageOuterClass.getDescriptor();
    com.leo.chat.proto.message.WordMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
